name: Build better-sqlite3 for cPanel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install patchelf
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get install -y patchelf

      - name: Build better-sqlite3
        run: |
          npm install better-sqlite3@10.4.1
          patchelf --clear-symbol-version log node_modules/better-sqlite3/build/Release/better_sqlite3.node
          patchelf --clear-symbol-version pow node_modules/better-sqlite3/build/Release/better_sqlite3.node
          patchelf --clear-symbol-version log2 node_modules/better-sqlite3/build/Release/better_sqlite3.node
          patchelf --clear-symbol-version exp node_modules/better-sqlite3/build/Release/better_sqlite3.node
          cp node_modules/better-sqlite3/build/Release/better_sqlite3.node ./better_sqlite3.node

      - uses: actions/upload-artifact@v4
        with:
          name: better-sqlite3-node24
          path: better_sqlite3.node
